services:
  analysis:
    image: nikip901/movie-revenue-test:efa0e81
    ports:
      - "8888:8888"
    volumes:
      - .:/project
      - renv_library:/project/renv/library

volumes:
  renv_library: