services:
  analysis:
    image: nikip901/movie-revenue-test:3b93bd1
    pull_policy: always
    ports:
      - "8888:8888"
    volumes:
      - .:/project
    environment:
      - RENV_PATHS_LIBRARY=/renv/library